# Generated by Django 4.1 on 2022-12-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('account', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'detail',
                'verbose_name_plural': 'details',
                'ordering': ('name',),
            },
        ),
    ]
