# Generated by Django 4.1 on 2022-12-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
