# Generated by Django 4.1 on 2022-12-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_remove_details_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('o', 'other')], default=2, max_length=30),
            preserve_default=False,
        ),
    ]
