# Generated by Django 4.1 on 2022-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('o', 'other')], default='M', max_length=30),
        ),
    ]
