# Generated by Django 4.1 on 2022-12-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='details',
            name='material',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
