# Generated by Django 4.1 on 2022-12-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0010_alter_details_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='material',
            field=models.CharField(max_length=200),
        ),
    ]
