# Generated by Django 4.1 on 2022-12-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0012_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='images',
        ),
    ]
